name: "Labels: Approved"

concurrency:
  group: labels
  cancel-in-progress: false
  queue: max

on:
  pull_request_review:
    types: [submitted]
jobs:
  add_label:
    # Change the repository name after you've made sure the team name is correct for your fork!
    # Hardlight: repo changed (space-wizards/space-station-14 < HardLightSector/HardLight)
    if: ${{ (github.repository == 'HardLightSector/HardLight') && (github.event.review.state == 'APPROVED') }}
    permissions:
      contents: read
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Add approved label
      if: ${{ contains(fromJSON('["OWNER", "MEMBER", "COLLABORATOR"]'), github.event.review.author_association) }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        REPO: ${{ github.repository }}
      run: |
        gh api --method POST "repos/$REPO/issues/$PR_NUMBER/labels" \
          --field labels[]="S: Approved"
